//! EXIF orientation.
//!
//! A phone writes the sensor's pixels unrotated and records how the device
//! was held in a tag. A viewer that ignores the tag shows the photo on its
//! side — and so does a thumbnail generated by ignoring it.
//!
//! Only the orientation is read. Everything else in the EXIF block is
//! DROPPED, and that is not a feature this module implements: re-encoding
//! from decoded pixels carries no metadata forward, so GPS coordinates,
//! serial numbers and timestamps do not survive a pass through this engine.
//! Preserving them would be the hard path, and for user uploads it is the
//! wrong default — a holiday photo carries the house's coordinates.

use exif::{In, Reader, Tag, Value};
use std::io::Cursor;

/// The eight EXIF orientations, as the transform needed to upright the image.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Orientation {
    Normal,
    FlipHorizontal,
    Rotate180,
    FlipVertical,
    Transpose,
    Rotate90,
    Transverse,
    Rotate270,
}

impl Orientation {
    fn from_tag(value: u16) -> Self {
        match value {
            2 => Self::FlipHorizontal,
            3 => Self::Rotate180,
            4 => Self::FlipVertical,
            5 => Self::Transpose,
            6 => Self::Rotate90,
            7 => Self::Transverse,
            8 => Self::Rotate270,
            // 1, and anything outside the range. An out-of-range value is a
            // malformed file, not an instruction — leaving the pixels alone
            // is the only safe reading.
            _ => Self::Normal,
        }
    }

    /// Whether applying this swaps width and height.
    pub fn swaps_axes(self) -> bool {
        matches!(
            self,
            Self::Transpose | Self::Rotate90 | Self::Transverse | Self::Rotate270
        )
    }
}

/// Read the orientation, or `Normal` when there is none.
///
/// A missing, unreadable or absent tag is not an error: most PNGs have no
/// EXIF at all, and a corrupt block in an otherwise decodable JPEG should
/// cost the rotation, not the upload.
pub fn orientation(bytes: &[u8]) -> Orientation {
    let mut cursor = Cursor::new(bytes);
    let Ok(exif) = Reader::new().read_from_container(&mut cursor) else {
        return Orientation::Normal;
    };
    let Some(field) = exif.get_field(Tag::Orientation, In::PRIMARY) else {
        return Orientation::Normal;
    };
    match field.value {
        Value::Short(ref values) => values
            .first()
            .map(|value| Orientation::from_tag(*value))
            .unwrap_or(Orientation::Normal),
        _ => Orientation::Normal,
    }
}
